"""PDF Analyst Report Generator for FinSight."""
import os
from datetime import datetime
from typing import List, Optional
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.graphics.charts.barcharts import VerticalBarChart

from src.models import CompanyHealthScore, FinancialMetrics, RedFlag


def generate_analyst_report(
    health_score: CompanyHealthScore,
    metrics: FinancialMetrics,
    redflags: List[RedFlag],
    output_path: Optional[str] = None
) -> str:
    """Generate a one-page PDF analyst report for a company.
    
    Returns the path to the generated PDF file.
    """
    company = health_score.company
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    if output_path is None:
        output_path = f"reports/{company}_analyst_report_{timestamp}.pdf"
    
    # Ensure reports directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Create PDF document
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=0.6*inch,
        leftMargin=0.6*inch,
        topMargin=0.8*inch,
        bottomMargin=0.8*inch
    )
    
    # Container for elements
    elements = []
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1a1a2e'),
        spaceAfter=12,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#666666'),
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#16213e'),
        spaceAfter=8,
        fontName='Helvetica-Bold'
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#333333'),
        spaceAfter=6,
        alignment=TA_JUSTIFY
    )
    
    # Color mapping for traffic light
    color_map = {
        "green": colors.HexColor('#22c55e'),
        "amber": colors.HexColor('#f59e0b'),
        "red": colors.HexColor('#ef4444')
    }
    
    # Header
    elements.append(Paragraph(f"{company} Analyst Report", title_style))
    elements.append(Paragraph(f"Generated by FinSight AI | {datetime.now().strftime('%B %d, %Y')}", subtitle_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Health Score Card
    score_color = color_map.get(health_score.color_code, colors.grey)
    
    score_data = [
        [Paragraph(f"<b>Overall Health Score</b>", heading_style), 
         Paragraph(f"<b>{health_score.overall_score:.0f}/100</b>", ParagraphStyle('Score', parent=body_style, fontSize=18, textColor=score_color))],
        [Paragraph(f"<b>Verdict:</b> {health_score.verdict}", body_style),
         Paragraph(f"<b>Status:</b> <font color='#{score_color.hexval()[2:]}'>●</font> {health_score.color_code.upper()}", body_style)],
    ]
    
    score_table = Table(score_data, colWidths=[3.5*inch, 2.5*inch])
    score_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
        ('BOX', (0, 0), (-1, -1), 2, score_color),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 0.15*inch))
    
    # Investment Rationale
    elements.append(Paragraph("<b>Investment Rationale</b>", heading_style))
    elements.append(Paragraph(health_score.one_line_reason, body_style))
    elements.append(Spacer(1, 0.15*inch))
    
    # Dimension Scores Table
    elements.append(Paragraph("<b>Health Score Breakdown</b>", heading_style))
    
    dim_data = [
        ['Dimension', 'Score', 'Weight', 'Rating'],
        ['Profitability', f"{health_score.profitability_score:.0f}", '35%', _get_rating(health_score.profitability_score)],
        ['Growth', f"{health_score.growth_score:.0f}", '30%', _get_rating(health_score.growth_score)],
        ['Debt Safety', f"{health_score.debt_safety_score:.0f}", '20%', _get_rating(health_score.debt_safety_score)],
        ['Risk Profile', f"{health_score.risk_score:.0f}", '15%', _get_rating(health_score.risk_score)],
    ]
    
    dim_table = Table(dim_data, colWidths=[1.8*inch, 1*inch, 1*inch, 1.5*inch])
    dim_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f1f5f9')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
        ('ALIGN', (1, 1), (2, -1), 'CENTER'),
        ('ALIGN', (3, 1), (3, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(dim_table)
    elements.append(Spacer(1, 0.2*inch))
    
    # Key Metrics Table
    elements.append(Paragraph("<b>Key Financial Metrics</b>", heading_style))
    
    metrics_data = [
        ['Metric', 'Value'],
        ['Revenue', f"₹{metrics.revenue_crore:,.0f} Cr" if metrics.revenue_crore else "N/A"],
        ['Net Profit', f"₹{metrics.net_profit_crore:,.0f} Cr" if metrics.net_profit_crore else "N/A"],
        ['EPS', f"₹{metrics.eps:.2f}" if metrics.eps else "N/A"],
        ['Debt/Equity', f"{metrics.debt_to_equity:.2f}x" if metrics.debt_to_equity else "N/A"],
        ['Revenue Growth', f"{metrics.yoy_revenue_growth_pct:.1f}%" if metrics.yoy_revenue_growth_pct else "N/A"],
        ['Operating Margin', f"{metrics.operating_margin_pct:.1f}%" if metrics.operating_margin_pct else "N/A"],
        ['ROE', f"{metrics.roe:.1f}%" if metrics.roe else "N/A"],
    ]
    
    metrics_table = Table(metrics_data, colWidths=[2.5*inch, 2.5*inch])
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#334155')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8fafc')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
        ('ALIGN', (1, 1), (1, -1), 'RIGHT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(metrics_table)
    elements.append(Spacer(1, 0.2*inch))
    
    # Red Flags Section
    elements.append(Paragraph("<b>Risk Assessment</b>", heading_style))
    
    if redflags:
        high_risks = [f for f in redflags if f.severity == "high"]
        medium_risks = [f for f in redflags if f.severity == "medium"]
        
        risk_text = f"""
        <b>Red Flags Detected:</b> {len(redflags)} total
        <br/>&nbsp;&nbsp;&nbsp;&nbsp;● High Severity: {len(high_risks)}
        <br/>&nbsp;&nbsp;&nbsp;&nbsp;● Medium Severity: {len(medium_risks)}
        <br/>&nbsp;&nbsp;&nbsp;&nbsp;● Low Severity: {len(redflags) - len(high_risks) - len(medium_risks)}
        """
        elements.append(Paragraph(risk_text, body_style))
        
        # List top 3 red flags
        if high_risks:
            elements.append(Paragraph("<b>Top Risks:</b>", ParagraphStyle('Bold', parent=body_style, fontName='Helvetica-Bold')))
            for i, rf in enumerate(high_risks[:3], 1):
                elements.append(Paragraph(f"{i}. {rf.keyword.upper()}: {rf.sentence[:100]}...", 
                                          ParagraphStyle('Small', parent=body_style, fontSize=9)))
    else:
        elements.append(Paragraph("<font color='#22c55e'>✓</font> No significant red flags detected. Risk profile appears favorable.", body_style))
    
    elements.append(Spacer(1, 0.2*inch))
    
    # Footer
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cbd5e1')))
    elements.append(Spacer(1, 0.1*inch))
    elements.append(Paragraph(
        "<i>This report is generated by FinSight AI for informational purposes only. It does not constitute investment advice. Always conduct your own due diligence before making investment decisions.</i>",
        ParagraphStyle('Disclaimer', parent=body_style, fontSize=8, textColor=colors.HexColor('#64748b'))
    ))
    
    # Build PDF
    doc.build(elements)
    
    return output_path


def _get_rating(score: float) -> str:
    """Get text rating based on score."""
    if score >= 80:
        return "Excellent"
    elif score >= 65:
        return "Good"
    elif score >= 50:
        return "Fair"
    elif score >= 35:
        return "Weak"
    else:
        return "Poor"


def generate_multi_company_report(
    health_scores: List[CompanyHealthScore],
    output_path: Optional[str] = None
) -> str:
    """Generate a comparison report for multiple companies."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    if output_path is None:
        output_path = f"reports/comparison_report_{timestamp}.pdf"
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                           rightMargin=0.6*inch, leftMargin=0.6*inch,
                           topMargin=0.8*inch, bottomMargin=0.8*inch)
    
    elements = []
    styles = getSampleStyleSheet()
    
    # Title
    elements.append(Paragraph("Multi-Company Comparison Report", styles['Heading1']))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
    elements.append(Spacer(1, 0.3*inch))
    
    # Comparison table
    headers = ['Company', 'Score', 'Verdict', 'Profit', 'Growth', 'Debt', 'Risk']
    data = [headers]
    
    for hs in health_scores:
        data.append([
            hs.company,
            f"{hs.overall_score:.0f}",
            hs.verdict,
            f"{hs.profitability_score:.0f}",
            f"{hs.growth_score:.0f}",
            f"{hs.debt_safety_score:.0f}",
            f"{hs.risk_score:.0f}"
        ])
    
    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f1f5f9')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    
    # Rankings
    elements.append(Spacer(1, 0.3*inch))
    elements.append(Paragraph("<b>Rankings by Overall Score</b>", styles['Heading2']))
    
    for i, hs in enumerate(sorted(health_scores, key=lambda x: x.overall_score, reverse=True), 1):
        elements.append(Paragraph(
            f"{i}. <b>{hs.company}</b> - Score: {hs.overall_score:.0f}, Verdict: {hs.verdict}",
            styles['Normal']
        ))
    
    doc.build(elements)
    return output_path
